# Site settings
title: Dorck's Blog
SEOTitle: 道轲的博客 | Dorck's Blog
header-img: img/home-bg.jpg
email: moosphon@gmail.com
description: "修技术之道，日三省吾身 | App Dev & Freelance Thinker & Hacker Growth | 这里是 @道轲(Dorck) 的个人博客，与你一起探寻世界。"
keyword: "Dorck, 道轲, Moosphan, 道轲的博客, Dorck Blog, Android, 技术, 博客, 个人博客, 专栏, 互联网, 设计, 黑客, 人生观, 设计"
url: "https://dorck.cn"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
#weibo_username:     Dorck
# zhihu_username:     yi-chang-mi-li-de-meng
github_username:    Moosphan
# twitter_username:   Dorck
#facebook_username:  Dorck
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Comment platforms

# Disqus settings
#disqus_username: Dorck

# Netease settings
netease_comment: false

# GitTalk comment settings
gitalk:
enable: true
owner: Moosphan
repo: moosphan.github.io
clientID: 4dd5cc4395d35d50d68b
clientSecret: 70898a0a9874bce8ff2dbcf62af1d2aff2184ab3
admin: Moosphan

# Giscus comment settings
giscus:
  repo: "Moosphan/Moosphan.github.io"
  category: "Comments"
  repo_id: "MDEwOlJlcG9zaXRvcnkzOTE1NzQ5OTU="
  category_id: "DIC_kwDOF1b1084CQ-Ty"
  mapping: 'pathname'
  input_position: 'top'
  theme: 'light_tritanopia'
  lang: "en"


# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'G-Y73B8QJZ9G'            # Format: UA-xxxxxx-xx
ga_domain: dorck.cn



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "道轲，编程语言/开源/极客路上的初行者。 <br> The universe is undecided, we are both dark horses."
sidebar-avatar: /img/logo.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "Jakewharton",
        href: "https://jakewharton.com/blog/"
    },{
        title: "Gityuan",
        href: "http://gityuan.com/"
    },{
        title: "维术",
        href: "http://weishu.me/"
    },{
        title: "damajia",
        href: "https://daimajia.com"
    },{
        title: "IceHe",
        href: "https://icehe.life/"
    },{
        title: "wanandroid",
        href: "https://www.wanandroid.com/"
    },{
        title: "江子健",
        href: "https://www.paincker.com"
    },{
        title: "武培轩",
        href: "https://www.cnblogs.com/wupeixuan"
    },{
        title: "Trinea",
        href: "https://www.trinea.cn/"
    },{
        title: "Chris Banes",
        href: "https://chris.banes.dev/"
    },{
        title: "Bennyhuo",
        href: "https://www.bennyhuo.com"
    },{
        title: "技术小黑屋",
        href: "https://droidyue.com/"
    },{
        title: "森哥",
        href: "https://johnsonlee.io"
    },{
        title: "2BAB",
        href: "https://2bab.me"
    },{
        title: "LeadroyaL",
        href: "https://www.leadroyal.cn"
    },{
        title: "Yujinyan",
        href: "https://blog.yujinyan.me"
    }
]
